### ISSUE TITLE
ShadowRoot | HTMLElement Event Handling Interchangeability

### ISSUE THREAD

**Issue by Offroaders123** [BenjaminAster/Better-TypeScript#2]
### Initial find

I was working on one of my Web Components, and I realized that TypeScript doesn't follow with what you can do in the browser, which is adding element-like event handlers to the Shadow Root. This doesn't appear to have parallel definitions over in TypeScript-land.

### Shadow Root interface comparisons

This is the definition for the `HTMLElementEventMap` interface, which extends from `ElementEventMap` and `GlobalEventHandlersEventMap`.

```ts
interface HTMLElementEventMap extends ElementEventMap, GlobalEventHandlersEventMap {}
```

In contrast, this is what the `ShadowRootEventMap` interface definition looks like.

```ts
interface ShadowRootEventMap {
  "slotchange": Event;
}
```

However, looking into the spec, it seems like these events aren't specified to be something that you can use on a `ShadowRoot` object, while they do indeed appear to work in the browser.

[ShadowRoot - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot)

### Possible improvements

This is what the improved event map would look like which could allow these event listeners to be used accordingly in TypeScript.

```ts
interface ShadowRootEventMap extends GlobalEventHandlersEventMap {}
```

I'm not completely sure if it should be fully synonymous type-wise with the `Document` interface's `DocumentEventMap`, to include the more high-level page events like `"fullscreenchange"` and such. I'll have to do some more testing on whether they are actually applicable to Shadow Roots or not. One argument could be said that they are most likely semi-interchangeable since that's partly the reasoning behind having Shadow Roots, so I think these events likely are listenable from within them. And the verbiage around `DocumentOrShadowRoot` which is present in both MDN and TypeScript makes the lines a bit blurry as to which things each are interchangeable with. Sorry to ramble a bit here, trying to figure things out with this, on the fly.

### Alternative take on things

After looking into the specs a little more than I with what I had known originally, this is probably unintended behavior on my part, I think this is only working in the browser because of event bubbling, and less so because of something supported that's undocumented. I thought I'd still go through mentioning this here though, as it was something interesting that I found that I hadn't looked into the reasoning behind yet.

### Reason for my use in the first place

My initial reason for adding event listeners to my Web Component with a Shadow DOM, to the Shadow DOM itself, is because I can safely depend on only focused elements within my Shadow DOM are accessible to my event listeners, which is something that I am managing a lot in my component, with focus state management.

```ts
// Method 1 - ShadowRoot-based event handling

declare global {
  // Required for proper `ShadowRoot.addEventListener()` types
  interface ShadowRootEventMap extends GlobalEventHandlersEventMap {}
}

// Partial Web Component pseudo-code
export class MenuDrop extends HTMLElement {
  declare readonly shadowRoot: ShadowRoot;

  constructor() {
    super();
    this.attachShadow({ mode: "open" });

    this.shadowRoot.addEventListener("pointerdown",event => {
      if (!(event.target instanceof HTMLElement)) return;

      if (event.pointerType === "mouse"){
        if ((event.button !== 0 && !event.target.matches("a")) || event.target.matches("menu-opener, menu-list")){
          event.preventDefault();
        }

        // ... further event handling code
      }
    });
  }
}
```

I think my initial reason for doing this handling directly on the `ShadowRoot` itself was because it makes it easier to essentially access the equivalent `event.target` of the Shadow DOM itself. If I were to add this same handler to just the parent component `MenuDrop` itself, then you have to use `event.composedPath()` to access that same element from within the Shadow DOM, because `event.target` will simply be the `MenuDrop` element itself when something in it's Shadow DOM has focus. So `event.target` in that scenario is of now help to you when you need to know about the component's Shadow DOM content specifically. That would then lead you to the `event.composedPath()` method instead, and that's a bit lengthier to use than simply just `event.target`, hence why I took the other route, if I remember right.

```ts
// Method 2 - Component-based event handling

// Partial Web Component pseudo-code
export class MenuDrop extends HTMLElement {
  declare readonly shadowRoot: ShadowRoot;

  constructor() {
    super();
    this.attachShadow({ mode: "open" });

    this.addEventListener("pointerdown",event => {
      const [target] = event.composedPath();
      if (!(target instanceof HTMLElement)) return;

      if (event.pointerType === "mouse"){
        if ((event.button !== 0 && !target.matches("a")) || target.matches("menu-opener, menu-list")){
          event.preventDefault();
        }

        // ... further event handling code
      }
    });
  }
}
```

### Wrap up

After writing that part out, it's not too much more to write just for adding the handling to the parent `MenuDrop` component instead of it's Shadow DOM, so maybe I will end up trying to work with that instead of the less explicit `this.shadowRoot.addEventListener()` method.

Sorry this was so long! Just learned a lot from this, thought it would be great to document here, especially in it's relation to TypeScript.

**Comment by BenjaminAster** [comment]
Thanks! Yep, that seems to be because all the DOM events bubble to the shadow root. I added the `interface ShadowRootEventMap extends GlobalEventHandlersEventMap {}` to Better-TypeScript@`0.1.1`.

**Comment by Offroaders123** [comment]
What are your thoughts on doing this, adding event listeners to the Shadow Root directly? While it does work, I'm curious if I should avoid it since it's not explicitly mentioned as something to do. Having thought about it, I haven't discovered any other projects that also do this to manage their component.

And another thought, I wonder if this has good/bad side effects, like that on components that *do* use this, it may be harder for the user to disable your component's standard behavior in the `event` object, with the methods like `preventDefault()`, `stopPropagation()`, and `stopImmediatePropagation()`. If the Shadow Root is open on the component, then I guess it would be still possible for the user to add their own event listener to the `this.shadowRoot` property also, to change the default behavior. This may not be straightforward in finding this out though. It could always be documented, which helps, but it also seems just as good, or rather better, to follow what all other standard elements do for this.

And I guess on the flip side, the good behavior that this brings is that if your intend on your Shadow Root being closed, then this will *help* you with encapsulating your component's event handling logic, since I think it could be disabled from the outside (I will have to do more testing on this), had you bound your event listeners to the component itself, rather than the Shadow Root. So if you have a closed Shadow Root, and you attach the listeners to the Shadow Root itself, then you can further protect the component from being modified by the outside page.

Once again, just trying to think this through. Thanks for adding this to Better-TypeScript!

**Comment by BenjaminAster** [comment]
To be honest, I have no idea what the best practices are here, but I guess in your case it really might make sense to rely on the event bubbling and add the listeners to the shadow root directly. I've rarely worked with shadow roots at all, so I guess you're really the expert here. The aim of bettter-typescript and new-javascript is also to reflect reality (everything a browser understands, TypeScript should understand, too), so I would definitely keep them in better-typescript.
